# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:
let
  inherit (haskellPackages) cabal binary cereal cipherAes128 cryptoApi cryptohashCryptoapi entropy HUnit mtl parallel prettyclass QuickCheck tagged testFramework testFrameworkHunit;
in cabal.mkDerivation (self: {
  pname = "DRBG";
  version = "0.5.4";
  src = ./.;
  buildDepends = [
    cereal cipherAes128 cryptoApi cryptohashCryptoapi entropy mtl
    parallel prettyclass tagged
  ];
  testDepends = [
    binary cereal cipherAes128 cryptoApi 
    cryptohashCryptoapi entropy HUnit mtl parallel prettyclass
    QuickCheck tagged testFramework testFrameworkHunit
  ];
  meta = {
    description = "Deterministic random bit generator (aka RNG, PRNG) based HMACs, Hashes, and Ciphers";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
